<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-service-05d32913-eedb-4f71-b8ef-718338b60ad1</UserSecretsId>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.template" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.template" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="INIFileParserDotNetCore" Version="2.5.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\app\DataPump.csproj" />
  </ItemGroup>
</Project>
