; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Gundi Radio Service"
#define MyAppVersion "1.0"
#define MyAppPublisher "Ai2 EarthRanger"
#define MyAppURL "earthranger.com"
#define MyAppExeName "RadioService.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{555CBF8F-6B67-4461-BB82-49E891FB2962}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\chris\source\repos\gundi-integration-kenwood\service\apache.org_licenses_LICENSE-2.0.txt
; InfoBeforeFile=C:\Users\chris\source\repos\gundi-integration-kenwood\service\information-before.txt
; InfoAfterFile=C:\Users\chris\source\repos\gundi-integration-kenwood\service\information.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=radioservice-install
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\EarthRanger\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\EarthRanger\appsettings.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\EarthRanger\Microsoft.Data.SqlClient.SNI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\EarthRanger\NLog.config"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]                                               
; Install the service
Filename: {sys}\sc.exe; Parameters: "create ""{#MyAppName}"" start=auto binpath=""{app}\{#MyAppExeName}"" displayname=""Gundi Radio Service"" "   ; Flags: runhidden;
; Set recovery options
Filename: {sys}\sc.exe; Parameters: "failure ""{#MyAppName}"" reset=0 actions=restart/60000/restart/120000/restart/180000 "   ; Flags: runhidden;
; Set a description
Filename: {sys}\sc.exe; Parameters: "description ""{#MyAppName}"" ""A Gundi/EarthRanger service that reads radio location data from KAS20 database."" "   ; Flags: runhidden;
; Start service
Filename: {sys}\sc.exe; Parameters: "start ""{#MyAppName}""";

[UninstallRun]
Filename: {sys}\sc.exe; Parameters: "start ""{#MyAppName}""";
Filename: {sys}\sc.exe; Parameters: "delete ""{#MyAppName}""";

[INI]
Filename: "{app}\settings.ini"; Section: gundi; Key: destination; String: "{code:GetGundiDestination}";
Filename: "{app}\settings.ini"; Section: gundi; Key: apikey; String: "{code:GetGundiApiKey}";
Filename: "{app}\settings.ini"; Section: gundi; Key: intervalMs; String: "5000";

Filename: "{app}\settings.ini"; Section: kas20; Key: server; String: "{code:GetKAS20Server}";
Filename: "{app}\settings.ini"; Section: kas20; Key: database; String: "{code:GetKAS20Database}";
Filename: "{app}\settings.ini"; Section: kas20; Key: username; String: "{code:GetKAS20Username}";
Filename: "{app}\settings.ini"; Section: kas20; Key: password; String: "{code:GetKAS20Password}";
Filename: "{app}\settings.ini"; Section: kas20; Key: system_id; String: "1";


[Code]

var
  GundiApiPage: TInputQueryWizardPage;
  KAS20Page: TInputQueryWizardPage;
  settings_filepath: string;
  
procedure InitializeWizard;
begin
  { Create the pages }
  
  GundiApiPage := CreateInputQueryPage(wpWelcome,
    'Gundi API Information', 
    'Please enter Gundi API, Token and Provider Key.',
    'These values determine which Gundi Connection the serivce will connect to. Your EarthRanger support team can provide this information.');
  GundiApiPage.Add('Gundi API Address:', False);
  GundiApiPage.Add('API Key:', False);


  KAS20Page := CreateInputQueryPage(GundiApiPage.ID,
    'KAS20 Database Connection Information', 
    'What are the connection parameters for your KAS-20 Database?',
    'These values indicate the hostname of your KAS-20 database and the credentials that {#MyAppName} will use to connect to it.');
  KAS20Page.Add('KAS-20 Server', False);
  KAS20Page.Add('KAS-20 Database', False);
  KAS20Page.Add('KAS-20 username', False);
  KAS20Page.Add('KAS-20 password', False);

  settings_filepath:= WizardDirValue + '\settings.ini';
  { Set default values, using settings that were stored last time if possible }
  GundiApiPage.Values[0] := GetIniString('gundi', 'destination', 'https://cdip-api-prod01.pamdas.org', settings_filepath);
  GundiApiPage.Values[1] := GetIniString('gundi', 'apikey', '', settings_filepath);
  KAS20Page.Values[0] := GetIniString('kas20', 'server', 'localhost', settings_filepath);
  KAS20Page.Values[1] := GetIniString('kas20', 'database', 'KAS20', settings_filepath);
  KAS20Page.Values[2] := GetIniString('kas20', 'user_id', 'KAS20Admin', settings_filepath);
  KAS20Page.Values[3] := GetIniString('kas20', 'password', 'admin', settings_filepath);

end;


function NextButtonClick(CurPageID: Integer): Boolean;
var
  I: Integer;
begin
  { Validate certain pages before allowing the user to proceed }
  if CurPageID = GundiApiPage.ID then begin
    if GundiApiPage.Values[0] = '' then begin
      MsgBox('You must enter a valid Gundi URL. Ex. "https://cdip-api-prod01.pamdas.org"', mbError, MB_OK)
      Result := False
    end else if GundiApiPage.Values[1] = '' then begin
        MsgBox('You must enter a valid Gundi API Key. You can get this from an EarthRanger Support team member.', mbError, MB_OK);
        Result := False;
    end else begin
        Result := True;
    end;

  end else if CurPageID = KAS20Page.ID then begin
    if KAS20Page.Values[0] = '' then begin
      MsgBox('You must enter a valid KAS-20 Servername. Ex. "localhost".', mbError, MB_OK)
      Result := False
    end else if KAS20Page.Values[1] = '' then begin
        MsgBox('You must enter a valid database name', mbError, MB_OK);
        Result := False;
    end else if KAS20Page.Values[2] = '' then begin
        MsgBox('You must enter a valid KAS-20 username', mbError, MB_OK);
        Result := False;
    end else if KAS20Page.Values[3] = '' then begin
        MsgBox('You must enter a valid KAS-20 password', mbError, MB_OK);
        Result := False;
    end else begin
        Result := True;
    end;
  end else
    Result := True;
end;

function GetGundiDestination(Param: String): String;
begin
  Result := GundiApiPage.Values[0];
end;

function GetGundiApiKey(Param: String): String;
begin
  Result := GundiApiPage.Values[1];
end;

function GetKAS20Server(Param: String): String;
begin
  Result := KAS20Page.Values[0];
end;

function GetKAS20Database(Param: String): String;
begin
  Result := KAS20Page.Values[1];
end;

function GetKAS20Username(Param: String): String;
begin
  Result := KAS20Page.Values[2];
end;

function GetKAS20Password(Param: String): String;
begin
  Result := KAS20Page.Values[3];
end;

{
 Helper functions
}
function FileReplaceString(const FileName, SearchString, ReplaceString: string):boolean;
var
  MyFile : TStrings;
  MyText : string;
begin
  MyFile := TStringList.Create;

  try
    result := true;

    try
      MyFile.LoadFromFile(FileName);
      MyText := MyFile.Text;

      { Only save if text has been changed. }
      if StringChangeEx(MyText, SearchString, ReplaceString, True) > 0 then
      begin;
        MyFile.Text := MyText;
        MyFile.SaveToFile(FileName);
      end;
    except
      result := false;
    end;
  finally
    MyFile.Free;
  end;
end;